# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\86156\Desktop\毕业设计\PyQt\camera.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_camera(object):
    def setupUi(self, camera):
        camera.setObjectName("camera")
        camera.resize(800, 500)
        camera.setMinimumSize(QtCore.QSize(800, 500))
        camera.setMaximumSize(QtCore.QSize(16777215, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\86156\\Desktop\\毕业设计\\PyQt\\icon/camera_window.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        camera.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(camera)
        self.centralwidget.setStyleSheet("background-color:rgb(21, 25, 46)")
        self.centralwidget.setObjectName("centralwidget")
        self.camera_video = QtWidgets.QLabel(self.centralwidget)
        self.camera_video.setGeometry(QtCore.QRect(50, 60, 500, 381))
        self.camera_video.setStyleSheet("background-color: rgb(32, 37, 63)")
        self.camera_video.setFrameShape(QtWidgets.QFrame.Box)
        self.camera_video.setFrameShadow(QtWidgets.QFrame.Raised)
        self.camera_video.setLineWidth(3)
        self.camera_video.setText("")
        self.camera_video.setObjectName("camera_video")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(600, 0, 151, 501))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.take_img = QtWidgets.QPushButton(self.layoutWidget)
        self.take_img.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("方正正纤黑简体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.take_img.setFont(font)
        self.take_img.setStyleSheet("QPushButton{\n"
"    background-color: rgb(76, 81, 127);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:15px;\n"
"    icon: url(./icon/take_icon.png);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(119, 123, 177);\n"
"}")
        self.take_img.setIconSize(QtCore.QSize(30, 30))
        self.take_img.setObjectName("take_img")
        self.verticalLayout.addWidget(self.take_img)
        self.retake_img = QtWidgets.QPushButton(self.layoutWidget)
        self.retake_img.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("方正正纤黑简体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.retake_img.setFont(font)
        self.retake_img.setStyleSheet("QPushButton{\n"
"    background-color: rgb(76, 81, 127);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:15px;\n"
"    icon: url(./icon/retake_icon.png);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(119, 123, 177);\n"
"}")
        self.retake_img.setIconSize(QtCore.QSize(30, 30))
        self.retake_img.setObjectName("retake_img")
        self.verticalLayout.addWidget(self.retake_img)
        self.confirm_img = QtWidgets.QPushButton(self.layoutWidget)
        self.confirm_img.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("方正正纤黑简体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.confirm_img.setFont(font)
        self.confirm_img.setStyleSheet("QPushButton{\n"
"    background-color: rgb(76, 81, 127);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:15px;\n"
"    icon: url(./icon/confirm_icon.png);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(119, 123, 177);\n"
"}")
        self.confirm_img.setIconSize(QtCore.QSize(30, 30))
        self.confirm_img.setObjectName("confirm_img")
        self.verticalLayout.addWidget(self.confirm_img)
        self.cancel_img = QtWidgets.QPushButton(self.layoutWidget)
        self.cancel_img.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("方正正纤黑简体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cancel_img.setFont(font)
        self.cancel_img.setStyleSheet("QPushButton{\n"
"    background-color: rgb(76, 81, 127);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:15px;\n"
"    icon: url(./icon/cancel_icon.png);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(119, 123, 177);\n"
"}")
        self.cancel_img.setIconSize(QtCore.QSize(30, 30))
        self.cancel_img.setObjectName("cancel_img")
        self.verticalLayout.addWidget(self.cancel_img)
        camera.setCentralWidget(self.centralwidget)

        self.retranslateUi(camera)
        self.cancel_img.clicked.connect(camera.exit_camera)
        self.take_img.clicked.connect(camera.take_photo)
        self.retake_img.clicked.connect(camera.retake_photo)
        self.confirm_img.clicked.connect(camera.confirm_photo)
        QtCore.QMetaObject.connectSlotsByName(camera)

    def retranslateUi(self, camera):
        _translate = QtCore.QCoreApplication.translate
        camera.setWindowTitle(_translate("camera", "相机拍照"))
        self.take_img.setText(_translate("camera", "拍 照"))
        self.retake_img.setText(_translate("camera", "重 拍"))
        self.confirm_img.setText(_translate("camera", "确 定"))
        self.cancel_img.setText(_translate("camera", "取 消"))
