# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\86156\Desktop\毕业设计\PyQt\cod.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cod(object):
    def setupUi(self, cod):
        cod.setObjectName("cod")
        cod.resize(1200, 700)
        cod.setMinimumSize(QtCore.QSize(1200, 700))
        cod.setMaximumSize(QtCore.QSize(1200, 700))
        font = QtGui.QFont()
        font.setKerning(False)
        cod.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\86156\\Desktop\\毕业设计\\PyQt\\icon/main_window.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        cod.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(cod)
        self.centralwidget.setStyleSheet("background-color:rgb(21, 25, 46)")
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 570, 1201, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.main_btn = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.main_btn.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.main_btn.setContentsMargins(80, 0, 80, 0)
        self.main_btn.setSpacing(40)
        self.main_btn.setObjectName("main_btn")
        self.sel_img = QtWidgets.QPushButton(self.layoutWidget)
        self.sel_img.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("方正正纤黑简体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sel_img.setFont(font)
        self.sel_img.setStyleSheet("QPushButton{\n"
"    background-color: rgb(76, 81, 127);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:15px;\n"
"    icon: url(./icon/sel_icon.png);\n"
"    hover{background-color: rgb(112, 119, 186)};\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(119, 123, 177);\n"
"}")
        self.sel_img.setIconSize(QtCore.QSize(30, 30))
        self.sel_img.setObjectName("sel_img")
        self.main_btn.addWidget(self.sel_img)
        self.open_cmr = QtWidgets.QPushButton(self.layoutWidget)
        self.open_cmr.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("方正正纤黑简体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.open_cmr.setFont(font)
        self.open_cmr.setStyleSheet("QPushButton{\n"
"    background-color: rgb(76, 81, 127);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:15px;\n"
"    icon: url(./icon/camera_icon.png);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(119, 123, 177);\n"
"}")
        self.open_cmr.setIconSize(QtCore.QSize(30, 30))
        self.open_cmr.setObjectName("open_cmr")
        self.main_btn.addWidget(self.open_cmr)
        self.start_cod = QtWidgets.QPushButton(self.layoutWidget)
        self.start_cod.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("方正正纤黑简体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.start_cod.setFont(font)
        self.start_cod.setStyleSheet("QPushButton{\n"
"    background-color: rgb(76, 81, 127);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:15px;    \n"
"    icon: url(./icon/cod_icon.png);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(119, 123, 177);\n"
"}")
        self.start_cod.setIconSize(QtCore.QSize(30, 30))
        self.start_cod.setObjectName("start_cod")
        self.main_btn.addWidget(self.start_cod)
        self.save_img = QtWidgets.QPushButton(self.layoutWidget)
        self.save_img.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("方正正纤黑简体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.save_img.setFont(font)
        self.save_img.setStyleSheet("QPushButton{\n"
"    background-color: rgb(76, 81, 127);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:15px;\n"
"    icon: url(./icon/save_icon.png);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(119, 123, 177);\n"
"}")
        self.save_img.setIconSize(QtCore.QSize(30, 30))
        self.save_img.setObjectName("save_img")
        self.main_btn.addWidget(self.save_img)
        self.ext = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ext.sizePolicy().hasHeightForWidth())
        self.ext.setSizePolicy(sizePolicy)
        self.ext.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("方正正纤黑简体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ext.setFont(font)
        self.ext.setStyleSheet("QPushButton{\n"
"    background-color: rgb(76, 81, 127);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:15px;\n"
"    icon: url(./icon/ext_icon.png);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(119, 123, 177);\n"
"}\n"
"")
        self.ext.setIconSize(QtCore.QSize(30, 30))
        self.ext.setObjectName("ext")
        self.main_btn.addWidget(self.ext)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 130, 1201, 401))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.img_show = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.img_show.setContentsMargins(80, 0, 80, 0)
        self.img_show.setSpacing(50)
        self.img_show.setObjectName("img_show")
        self.ori_img = QtWidgets.QLabel(self.layoutWidget1)
        self.ori_img.setStyleSheet("background-color: rgb(32, 37, 63)")
        self.ori_img.setFrameShape(QtWidgets.QFrame.Box)
        self.ori_img.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ori_img.setLineWidth(3)
        self.ori_img.setText("")
        self.ori_img.setObjectName("ori_img")
        self.img_show.addWidget(self.ori_img)
        self.cod_img = QtWidgets.QLabel(self.layoutWidget1)
        self.cod_img.setStyleSheet("background-color: rgb(32, 37, 63)")
        self.cod_img.setFrameShape(QtWidgets.QFrame.Box)
        self.cod_img.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cod_img.setLineWidth(3)
        self.cod_img.setText("")
        self.cod_img.setObjectName("cod_img")
        self.img_show.addWidget(self.cod_img)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(630, 60, 491, 51))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.sel_show = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.sel_show.setContentsMargins(30, 0, 30, 0)
        self.sel_show.setSpacing(30)
        self.sel_show.setObjectName("sel_show")
        self.ori_show = QtWidgets.QPushButton(self.layoutWidget2)
        self.ori_show.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("方正正纤黑简体")
        font.setPointSize(12)
        self.ori_show.setFont(font)
        self.ori_show.setStyleSheet("QPushButton{\n"
"    background-color: rgb(76, 81, 127);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"    icon: url(./icon/show_icon.png);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(119, 123, 177);\n"
"}")
        self.ori_show.setObjectName("ori_show")
        self.sel_show.addWidget(self.ori_show)
        self.ori_hide = QtWidgets.QPushButton(self.layoutWidget2)
        self.ori_hide.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("方正正纤黑简体")
        font.setPointSize(12)
        self.ori_hide.setFont(font)
        self.ori_hide.setStyleSheet("QPushButton{\n"
"    background-color: rgb(76, 81, 127);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"    icon: url(./icon/hide_icon.png);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(119, 123, 177);\n"
"}")
        self.ori_hide.setObjectName("ori_hide")
        self.sel_show.addWidget(self.ori_hide)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 50, 481, 41))
        font = QtGui.QFont()
        font.setFamily("方正兰亭粗黑_GBK")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255, 255, 255)")
        self.label.setObjectName("label")
        cod.setCentralWidget(self.centralwidget)

        self.retranslateUi(cod)
        self.sel_img.clicked.connect(cod.select_image)
        self.ext.clicked.connect(cod.exit_app)
        self.open_cmr.clicked.connect(cod.open_camera)
        self.start_cod.clicked.connect(cod.cod_image)
        self.ori_show.clicked.connect(cod.ori_image_show)
        self.ori_hide.clicked.connect(cod.ori_image_hide)
        self.save_img.clicked.connect(cod.save_image)
        QtCore.QMetaObject.connectSlotsByName(cod)

    def retranslateUi(self, cod):
        _translate = QtCore.QCoreApplication.translate
        cod.setWindowTitle(_translate("cod", "伪装目标检测"))
        self.sel_img.setText(_translate("cod", "选择图片"))
        self.open_cmr.setText(_translate("cod", "打开相机"))
        self.start_cod.setText(_translate("cod", "开始检测"))
        self.save_img.setText(_translate("cod", "保存结果"))
        self.ext.setText(_translate("cod", "退出程序"))
        self.ori_show.setText(_translate("cod", "显示原图"))
        self.ori_hide.setText(_translate("cod", "去除原图"))
        self.label.setText(_translate("cod", "伪 装 目 标 检 测"))
